version: '3.3'
services:
    zigbee2soco:
        build: .
        restart: always
        network_mode: host
        image: zigbee2soco
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        environment:
          - PREFIX=zigbee2mqtt/SONOS-remote
          - MQTT_HOST=localhost
          - MQTT_PORT=1883
          - MQTT_USER=
          - MQTT_PASS=
          - VOLUME_MULTIPLIER=2
          
