services:
    zigbee2soco:
        build: .
        restart: always
        network_mode: host
        image: zigbee2soco
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        env_file:
          - .env
        environment:
          PREFIX: ${PREFIX:-zigbee2mqtt/Woonkamer Sonos}
          MQTT_HOST: ${MQTT_HOST:-localhost}
          MQTT_PORT: ${MQTT_PORT:-1883}
          MQTT_USER: ${MQTT_USER:-}
          MQTT_PASS: ${MQTT_PASS:-}
          VOLUME_MULTIPLIER: ${VOLUME_MULTIPLIER:-2}
          SONOS_ZONE: ${SONOS_ZONE:-Woonkamer Sonos}
        cap_add:
        - NET_ADMIN
        - SYS_ADMIN